cc_library(
    name = "posix",
    copts = ["-std=c++14"],
    srcs = glob(["*.cpp"]),
    deps = [
        "//filesys:hdrs",
        "//third_party/glog:glog"
    ],
    visibility = ["//visibility:public"]
)
