#-
# Copyright (c) 2016-2017 Doug Rabson
# All rights reserved.
#

cc_library(
    name = "mem",
    copts = ["-std=c++14"],
    srcs = glob(["*.cpp"]),
    hdrs = ["mem.h"],
    deps = [
        "//keyval:hdrs",
    ],
    visibility = ["//visibility:public"]
)
